version: '3'
services:
  bills:
    image: lokeshkumar9908/billspaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  buses:
    image: lokeshkumae9908/busespaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  tickets:
    image: lokeshkumar9908/ticketspaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  movies:
    image: lokeshkumar9908/moviespaytm:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
