version: '3'
services:
  bills:
    image: lokeshkumar9908/tigergoogle:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  buses:
    image: lokeshkumar9908/liongoogle:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  tickets:
    image: lokeshkumar9908/ratgoogle:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  movies:
    image: lokeshkumar9908/rabbitgoogle:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
